POST http://localhost:3333/videos
Content-type: application/json

{
    "title": "Video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

###
PUT http://localhost:3333/videos/5f3e7cfd-60b9-4b60-8f02-ca1c260de3fb
Content-type: application/json

{
    "title": "Video 002",
    "description": "Esse é o aaaaaa vídeo",
    "duration": 180
}


###

DELETE http://localhost:3333/videos/5f3e7cfd-60b9-4b60-8f02-ca1c260de3fb